version: "3.8"
services:
  frontend:
    build: ./frontend-2
    ports:
      - 3000:3000
  backend:
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      - database
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - algol007:/data/db

volumes:
  algol007:
